### ISSUE TITLE
When autoreconnect is enabled, disconnect must stop reconnect cycle

### ISSUE THREAD

**Issue by manas-chaudhari** [eclipse-paho/paho.mqtt.java#592] opened 2018-10-08 10:14 UTC
- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

Currently, when invoking connect with autoReconnect enabled, there's no way to close the connection.

Consider the case when connection is no longer required, and we want to close the connection. Also, we might need to connect soon, so we don't want to close the client.

Now, if the client is already in disconnected state due to loss of internet connection, then calling `disconnect` results in a crash. And if disconnect is not called, then the reconnection cycle will keep trying to reconnect. 

Suggestion: If `connect` method creates a connection and sets up reconnect cycle, then `disconnect` method should destroy the connection AND stop the reconnection cycle.

If the connection is already destroyed, then it should at least stop the reconnection cycle.

**Comment by jpwsutton** [comment] 2018-10-19 06:43
This seems like a good improvement that could be made, it should all be do-able from within the MqttAsyncClient class. You're more than welcome to submit a PR that fixes this!

**Comment by icraggs** [comment] 2019-02-20 16:25
Duplicate of #425

**Closed as completed by icraggs** 2019-02-20 16:25 UTC
Labels: duplicate, enhancement, help wanted, good-first-issue
