### ISSUE TITLE
no NetworkModule installed for scheme "tcp" of URI "tcp://129.1.99.8:1883"

### ISSUE THREAD

**Issue by i402097836** [eclipse-paho/paho.mqtt.java#672] opened 2019-05-08 06:17 UTC
Please fill out the form below before submitting, thank you!

- [yes ] Bug exists Release Version 1.2.1 ( Master Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new
 

This seems like a bug in a multithreaded environment

**Comment by icraggs** [comment] 2019-09-26 14:59
Hi.  This is a duplicate of #572 - please follow there.  Thanks.

**Closed as completed by icraggs** 2019-09-26 14:59 UTC
Labels: duplicate
