### ISSUE TITLE
no NetworkModule installed for scheme "tcp" of URI "tcp://47.112.200.32:1883"，请问怎么解决？直接使用org.eclipse.paho.client.mqttv3.1.2.1.jar包没有问题

### ISSUE THREAD

**Issue by jiangwenjing69** [eclipse-paho/paho.mqtt.java#699] opened 2019-09-19 05:48 UTC
下载的Java版paho.mqtt.java的org.eclipse.paho.client.mqttv3的源码包，eclipse编译MQTT通信客户端，报错：Exception in thread "Thread-6" java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://47.112.200.32:1883"
	at org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.validateURI(NetworkModuleService.java:70)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:454)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:315)
	at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:227)
	at sys.mqtt3.ClientMQTT.connect(ClientMQTT.java:31)
	at sys.mqtt3.ClientMQTT.run(ClientMQTT.java:130)

**Comment by icraggs** [comment] 2019-09-26 14:58
Hi.  This is a duplicate of #572.  Please follow in there.  Thanks.

**Closed as completed by icraggs** 2019-09-26 14:58 UTC
Labels: duplicate
