### ISSUE TITLE
ConnectionLost from Websocket

### ISSUE THREAD

**Issue by NampyoJeong** [eclipse-paho/paho.mqtt.java#349] opened 2017-04-04 07:29 UTC
Please fill out the form below before submitting, thank you!

- [v] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

wss://iot.eclipse.org:443/ws
ws://iot.eclipse.org:80/ws

I tried both of these URLs, but I could not connect them.
With the same settings, it works fine in 1.1.0 version but it does not work in 1.1.1 version.

This is my log.

04-04 16:11:18.003 21031-21354/com.example.mqtttest D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.ExampleAndroidClient
04-04 16:11:18.013 21031-21354/com.example.mqtttest D/AlarmPingSender: Schedule next alarm at 1491289908027
04-04 16:11:18.013 21031-21354/com.example.mqtttest D/AlarmPingSender: Alarm scheule using setExact, delay: 30000
04-04 16:11:18.033 21031-21031/com.example.mqtttest I/System.out: LOG: Connected to: wss://iot.eclipse.org:443
04-04 16:11:18.313 21031-21031/com.example.mqtttest I/System.out: LOG: Subscribed!
04-04 16:11:19.323 21031-21354/com.example.mqtttest D/AlarmPingSender: Unregister alarmreceiver to MqttServiceExampleAndroidClient
04-04 16:11:19.353 21031-21354/com.example.mqtttest D/AlarmPingSender: Schedule next alarm at 1491289879462
04-04 16:11:19.353 21031-21354/com.example.mqtttest D/AlarmPingSender: Alarm scheule using setExact, delay: 100
04-04 16:11:19.353 21031-21031/com.example.mqtttest I/System.out: LOG: The Connection was lost.
04-04 16:11:21.683 21031-21863/com.example.mqtttest D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.ExampleAndroidClient
04-04 16:11:21.693 21031-21863/com.example.mqtttest D/AlarmPingSender: Schedule next alarm at 1491289911702
04-04 16:11:21.693 21031-21863/com.example.mqtttest D/AlarmPingSender: Alarm scheule using setExact, delay: 30000
04-04 16:11:21.703 21031-21031/com.example.mqtttest I/System.out: LOG: Reconnected to : wss://iot.eclipse.org:443
04-04 16:11:21.993 21031-21031/com.example.mqtttest I/System.out: LOG: Subscribed!

**Comment by maartenl945** [comment] 2017-05-03 08:27
I get the same problem here. Initial connect with paho client reports ok, but it is immediately followed by a connection lost callback call. And than a cycle of reconnect attempts repeats every second as we are using the automatic reconnect feature:

2017-05-03 08:43:59,356 INFO  MQTT Call: 481e630b-e3c5-4962-b691-e9c7663ea948 [com.wps.pms.cloudreportingconnector.mqtt.MqttReportingPublisher] : Connect complete to server ws://host-deleted-on-purpose:8083, reconnect is true, bufferedMessage = 0
2017-05-03 08:44:00,358 INFO  MQTT Rec: 481e630b-e3c5-4962-b691-e9c7663ea948 [com.wps.pms.cloudreportingconnector.mqtt.MqttReportingPublisher] : Connection lost {}
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164) [org.eclipse.paho.client.mqttv3-100.1.1.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.7.0_95]
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-100.1.1.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116) ~[org.eclipse.paho.client.mqttv3-100.1.1.jar:?]
        ... 1 more

**Comment by NampyoJeong** [comment] 2017-07-20 07:33
It is ok for version 1.1.2-SNAPSHOT to me.

**Comment by jpwsutton** [comment] 2018-08-28 19:56
Thanks @NampyoJeong, I'll close this issue now then as we will be releasing the next version soon.

**Closed as completed by jpwsutton** 2018-08-28 19:56 UTC
Labels: triage
