### ISSUE TITLE
Failed to receive MQTT events 

### ISSUE THREAD

**Issue by dileepmandapam** [eclipse-paho/paho.mqtt.java#729] opened 2020-01-06 13:57 UTC
**Problem**
I am facing an intermittent issue where the MQTT subscriber failed to receive events from the broker even though the client is connected to the broker. I am verifying  client connection status by using _mqttClient.isConnected()_ API.

**Context**
Establishing an MQTT connection with the below connection options. 
**automaticReconnect: false.
keep-alive: 30 seconds
clean session: false
Paho client version: 1.2.0.** 

**Reconnection handling** 
On connection loss, the client application callback waits for **2 minutes** and reconnects with the broker using _mqttClient.reconnect()_ API. 

Only when the subscriber client gets restarted/rebooted (once in 3 months) then new events are processed.

**Comment by BigKarel** [comment] 2020-01-08 09:19
I meet the same problem

**Comment by rdasgupt** [comment] 2020-01-10 19:50
What is your platform? 
Could you try with Paho client version 1.2.2?
Is this problem intermittent?

I couldn't recreate the problem with 1.2.2 on macOSX and centos 7.
Here is my sample code to recreate and debug:
[SubSample729.txt](https://github.com/eclipse/paho.mqtt.java/files/4047627/SubSample729.txt)

To create connection loss, I tried two options:
- Pulled the network cable out
- Used tcpkill to kill connections on source port 1883.

Compare my sample code with your client code and let me know the differences.

**Comment by rdasgupt** [comment] 2020-01-22 22:00
Refer to issue #719. Though the symptom is different, the root cause is same.
You can try the fix suggested for #719

**Comment by rdasgupt** [comment] 2020-04-01 03:51
Fixed by PR #719

**Closed as completed by rdasgupt** 2020-04-01 03:51 UTC
Labels: fix submitted
