### ISSUE TITLE
MqttClient.disconnectForcibly() blocked for the whole timeout

### ISSUE THREAD

**Issue by artembilan** [eclipse-paho/paho.mqtt.java#644] opened 2019-03-25 15:42 UTC
After upgrading to client `1.2.1` from `1.2.0` we are facing timing issue with the `disconnectForcibly()`.

The simple test-case to reproduce an issue:
```
public class MqttDisconnectDeadLockTests {

	@Test
	public void testDisconnect() throws MqttException {
		MqttClient mqttClient = new MqttClient("tcp://localhost:1883", "foo");
		mqttClient.connect();
                mqttClient.subscribe("foo", 1);
		mqttClient.unsubscribe("foo");
		mqttClient.disconnectForcibly(30_000);
	}

}
```

We are fully blocked to wait for those 30 seconds.

My hard debugging shows me that `CommsReceiver` gets an `java.io.EOFException` while waiting for the confirmation for a DISCONNECT message. I guess with meaning "Socket closed".

Thanks

**Comment by marcus-hiles** [comment] 2019-04-11 12:05
yeah, I was able to reproduce this issue ... hope the technical team has resolved this, so I can upgrade?

**Comment by desokroshan** [comment] 2019-04-15 23:43
I am planning to use disconnectForcibly() to recover from `Client is currently disconnecting (32102)` exception but it blocks and freezes the app. Any updates on this?

**Comment by desokroshan** [comment] 2019-06-17 20:07
Any updates on this?

**Comment by rdasgupt** [comment] 2020-01-23 13:18
Use the fix for #719  and enable automaticReconnect.

**Comment by rdasgupt** [comment] 2020-04-03 19:50
PR #719 is not working for this issue in the latest develop branch.
Looks like client waits for more than a minute to disconnect.

**Comment by rdasgupt** [comment] 2020-04-05 11:22
The current develop branch has fixes related to client hung cases. Using latest branch, I ran some tests. I think disconnectForcibly() is working as designed and documented. For detailed documentation refer to:
https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttClient.html

disconnectForcibly() : It will wait for a maximum of 30 seconds for work to quiesce before disconnecting and wait for a maximum of 10 seconds for sending the disconnect packet to server.

disconnectForcibly(long disconnectTimeout) : It will wait for a maximum of 30 seconds for work to quiesce before disconnecting.

Here are my test results:
Disconnect client. no timeout
Disconnect start: 2020-04-05 06:10:39.229
Disconnect   end: 2020-04-05 06:10:49.251    <== 10 sec

Disconnect client. timeout: 2000
Disconnect start: 2020-04-05 06:10:49.591
Disconnect   end: 2020-04-05 06:10:51.605   <== 2 sec

Disconnect client. timeout: 30000
Disconnect start: 2020-04-05 06:10:51.936
Disconnect   end: 2020-04-05 06:11:21.947  <== 30 sec

Disconnect client. timeout: 70000
Disconnect start: 2020-04-05 06:11:22.276
Disconnect   end: 2020-04-05 06:12:32.286   <=== test stopped by keepalive timeout of 60 seconds.

Though disconnectForcibly() is used in many test cases, I will add some explicit tests for disconnectForcibly().

**Comment by rdasgupt** [comment] 2020-04-05 15:40
I am closing this issue. If you do not agree with the details provided and still observe client going in hung state, please open a new issue with the following details:
- Use case
- Test case
- Paho logs - for details on how to capture paho client logs, refer to the following link:

https://wiki.eclipse.org/Paho/Log_and_Debug_in_the_Java_client

**Closed as completed by rdasgupt** 2020-04-05 15:40 UTC
