### ISSUE TITLE
NullPointerExceptionl when reconnect

### ISSUE THREAD

**Issue by lixiangers** [eclipse-paho/paho.mqtt.java#333] opened 2017-02-24 10:49 UTC
Bug exists Release Version 1.1.0 ( Master Branch)

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@419edd30
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:769)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5095)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
	at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
	at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
	at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:759)
	... 9 more
java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
	at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
	at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
	at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:759)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5095)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by jpwsutton** [comment] 2017-02-24 13:18
@lixiangers This looks like an error from the Android service and looks like it's a duplicate of this issue: https://github.com/eclipse/paho.mqtt.android/issues/101 Could you confirm that this happens on the latest build of the Android Service please? If the problem persists you could post [here](https://github.com/eclipse/paho.mqtt.android/issues/187) where another user is reporting the same issue.

**Closed as completed by jpwsutton** 2017-02-24 13:18 UTC

**Comment by lixiangers** [comment] 2017-02-27 02:19
@jpwsutton the build of Android Sevice is 1.1.1 
Gradle setting:
  compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
  compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
