### ISSUE TITLE
Crash due to failed to connect to Broker

### ISSUE THREAD

**Issue by longbkiter07** [eclipse-paho/paho.mqtt.java#220] opened 2016-07-22 03:00 UTC
- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.0.3 (Develop Branch)

I've got the crash issue due to Mqtt from Crashlytics. Here it is:

```
org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure (ConnectActionListener.java:120)
org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect (ConnectActionListener.java:189)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect (MqttAsyncClient.java:592)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect (MqttAsyncClient.java:1078)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.access$2 (MqttAsyncClient.java:1073)
org.eclipse.paho.client.mqttv3.MqttAsyncClient$ReconnectTask.run (MqttAsyncClient.java:1138)
```

Devices: HUAWEI G629-UL00, HUAWEI G610-U0050
Android versions: 4.2.1, 4.4.4

Because it runs on mqtt thread so I can not prevent the crash. So can you help me to fix it or suggest a work around to prevent it? 
Thanks a lots.

**Comment by jpwsutton** [comment] 2016-07-25 07:50
Hi, is this using the Pure Java library or the Android Library? Also, this doesn't look like the full stack trace, could you provide the full stack as well as exception message please?
Also, throwing an MqttException might be the expected behaviour in some cases, if you are using the java client, you should be catching the exception and handling it appropriately.

**Comment by longbkiter07** [comment] 2016-07-26 02:41
Actually the full stack trace is:

```
Fatal Exception: java.lang.NullPointerException
Attempt to get length of null array
 Raw Text
org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure (ConnectActionListener.java:120)
org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect (ConnectActionListener.java:189)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect (MqttAsyncClient.java:592)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect (MqttAsyncClient.java:1078)
org.eclipse.paho.client.mqttv3.MqttAsyncClient.access$2 (MqttAsyncClient.java:1073)
org.eclipse.paho.client.mqttv3.MqttAsyncClient$ReconnectTask.run (MqttAsyncClient.java:1138)
java.util.Timer$TimerImpl.run (Timer.java:284)
```

This is retry task, it does not relate to our code, so I could not do anything to catch the exception. I think `org.eclipse.paho.client.mqttv3.internal` is the java library, isn't it?

**Comment by gholadr** [comment] 2016-07-26 03:02
I've attached the entire log from Crashlytics for additional reference [com.squar.mychat.release_issue_14002_crash_5796bd8e03a9000123566cd9386fa198.txt](https://github.com/eclipse/paho.mqtt.java/files/382934/com.squar.mychat.release_issue_14002_crash_5796bd8e03a9000123566cd9386fa198.txt)

**Comment by jpwsutton** [comment] 2016-07-26 09:30
Thanks for the extra detail, the exception is being thrown because the array of networkmodules is null, this shouldn't happen as any invalid server URIs that would be used to create the network module would be caught much earlier on.  I suspect that the switch in createNetworkModule is reaching this default:

```
default:
            // This shouldn't happen, as long as validateURI() has been called.
            netModule = null;
```

But that would mean that your URI somehow managed to slip through validateURI which I don't think is really possible as an IllegalArgumentException would have been thrown if the URI was invalid.

Do you have an example of the Server URI that is being provided also, are you providing the URI directly to the connect call, or are you giving the connect options an array of URIs?

**Comment by jpwsutton** [comment] 2016-09-08 13:21
@longbkiter07 or @gholadr are you able to provide an example of the URI that's getting bast validateURI? I don't think we'll be able to resolve this bug otherwise.

**Comment by jpwsutton** [comment] 2018-08-28 17:54
Closing issue, as there hasn't been any response since 2016.

**Closed as completed by jpwsutton** 2018-08-28 17:54 UTC
Labels: bug
