### ISSUE TITLE
SSLSocketFactoryFactory.getTrustStore() when encodedPath=null will interrupt connect process

### ISSUE THREAD

**Issue by 54binge** [eclipse-paho/paho.mqtt.java#767] opened 2020-04-13 09:53 UTC
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.3 ( Master Branch)

```
public String getTrustStore(String configID) {
        String encodedPath = getProperty(configID, TRUSTSTORE, SYSTRUSTSTORE);
        try { 
            //encodedPath may null 
            String decodedPath = java.net.URLDecoder.decode(encodedPath, StandardCharsets.UTF_8.name());
            return decodedPath;
        } catch (UnsupportedEncodingException e) {
            return encodedPath;
        }
    }
```

**Comment by rdasgupt** [comment] 2020-04-13 11:40
@54binge 
The encodedPath will be null if both TRUSTSTORE and SYSTRUSTSTORE is not set. 
Could you provide more information on your use case? 
Was your client working with v1.2.2? If so I wonder how? The behavior of this method has not changed from v1.2.2.

**Comment by 54binge** [comment] 2020-04-14 07:27
@rdasgupt 
Thanks reply!you are right,both TRUSTSTORE and SYSTRUSTSTORE is not set, and i have not found that in android demo(may be it`s too old),it is not necessary to set the truststore in our use case, i think the log is confused. v1.2.2 works well, i use it instead. Thanks again!

**Comment by rdasgupt** [comment] 2020-04-14 14:52
@54binge 
You mentioned that v1.2.2 works. It means it is a regression in 1.2.3. I will check this out and fix the issue.

**Comment by 54binge** [comment] 2020-04-15 03:56
@rdasgupt
v1.2.3 add the decode process, when encodedPath is null, in method java.net.URLDecoder.decode( encodedPath, StandardCharsets.UTF_8.name()),then run code int numChars = s.length(); it will throw NPE,but not catch it outside(just catch UnsupportedEncodingException), then the expected process was interrupted！

**Comment by t-beckmann** [comment] 2020-04-15 07:07
Can confirm this bug, commit causing the issue is https://github.com/eclipse/paho.mqtt.java/commit/619d066a2b2c14be289b30c55ccf0d54235048d0. I downgraded to version 1.2.2 which is working correctly.

**Comment by rdasgupt** [comment] 2020-04-15 13:33
@54binge 
Your analysis is correct. Thanks for checking this out. I will fix the code.
Since this is a regression, I will add the fix in 1.2.4.

**Comment by rdasgupt** [comment] 2020-04-15 19:41
Issue resolved by PR #768

**Closed as completed by rdasgupt** 2020-04-15 19:41 UTC
Labels: bug

**Comment by fabiosassu-sysdata** [comment] 2020-04-16 08:59
Is there an ETA on when 1.2.3 is going to be retagged and released?

**Comment by rdasgupt** [comment] 2020-04-16 17:46
Service release v1.2.4 is released.

**Comment by fabiosassu-sysdata** [comment] 2020-04-16 18:15
I'll try it out, thanks!
