### ISSUE TITLE
Mqtt websocket attempts to reconnect throwing EOF exception

### ISSUE THREAD

**Issue by prmathur-microsoft** [eclipse-paho/paho.mqtt.java#358] opened 2017-04-17 18:46 UTC
Please fill out the form below before submitting, thank you!

- [x ] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

I'm successfully able to send messages however I land up in EOF exception in connectionlost after a while (after sending anywhere between 2-10 messages) This flow works perfectly fine with MQTT without websocket. Tracing it 
public void run() {
		final String methodName = "run";
		MqttToken token = null;

		while (running && (in != null)) {
			try {
				//@TRACE 852=network read message
				log.fine(CLASS_NAME,methodName,"852");
				receiving = in.available() > 0;
				MqttWireMessage message = in.readMqttWireMessage(); --------> exception here
				receiving = false;

				// instanceof checks if message is null
				if (message instanceof MqttAck) {
					token = tokenStore.getToken(message);
					if (token!=null) {
						synchronized (token) {
							// Ensure the notify processing is done under a lock on the token
							// This ensures that the send processing can complete  before the
							// receive processing starts! ( request and ack and ack processing
							// can occur before request processing is complete if not!
							clientState.notifyReceivedAck((MqttAck)message);
						}
					} else if(message instanceof MqttPubRec || message instanceof MqttPubComp || message instanceof MqttPubAck) {
						//This is an ack for a message we no longer have a ticket for.
						//This probably means we already received this message and it's being send again
						//because of timeouts, crashes, disconnects, restarts etc.
						//It should be safe to ignore these unexpected messages.
						log.fine(CLASS_NAME, methodName, "857");
					} else {
						// It its an ack and there is no token then something is not right.
						// An ack should always have a token assoicated with it.
						throw new MqttException(MqttException.REASON_CODE_UNEXPECTED_ERROR);
					}
				} else {
					if (message != null) {
						// A new message has arrived
						clientState.notifyReceivedMsg(message);
					}
				}
			}
			catch (MqttException ex) {
				//@TRACE 856=Stopping, MQttException
				log.fine(CLASS_NAME,methodName,"856",null,ex);
				running = false;
				// Token maybe null but that is handled in shutdown
				clientComms.shutdownConnection(token, ex);
			}
			catch (IOException ioe) {
				//@TRACE 853=Stopping due to IOException
				log.fine(CLASS_NAME,methodName,"853");

				running = false;
				// An EOFException could be raised if the broker processes the
				// DISCONNECT and ends the socket before we complete. As such,
				// only shutdown the connection if we're not already shutting down.
				if (!clientComms.isDisconnecting()) {
					clientComms.shutdownConnection(token, new MqttException(MqttException.REASON_CODE_CONNECTION_LOST, ioe)); -------> lands up here
				}
			}

Looking deeper - 

public MqttWireMessage readMqttWireMessage() throws IOException, MqttException {
		final String methodName ="readMqttWireMessage";
		
		MqttWireMessage message = null;
		try {
			// read header
			if (remLen < 0) {
				// Assume we can read the whole header at once.
				// The header is very small so it's likely we
				// are able to read it fully or not at all.
				// This keeps the parser lean since we don't
				// need to cope with a partial header.
				// Should we lose synch with the stream,
				// the keepalive mechanism would kick in
				// closing the connection.
				bais.reset();
				
				byte first = in.readByte(); ----------------------> exception here
				clientState.notifyReceivedBytes(1);

Once I receive the exception, reconnection attempts are never successful.

**Comment by prmathur-microsoft** [comment] 2017-04-17 18:48
This is definitely not a connection issue as I can successfully talk to server without websockets.

**Comment by binarybucks** [comment] 2017-04-20 17:53
It is definately not. More details, including a TCP dump can be found at https://github.com/owntracks/android/issues/448. 

The issue does not exist in the 1.1.0 build.

**Comment by prmathur-microsoft** [comment] 2017-04-20 18:03
I'm trying 1.1.1 master branch and I see this. Any ideas what could be happening here ?

**Comment by prmathur-microsoft** [comment] 2017-04-20 18:05
#349 also points to the same issue.

**Comment by binarybucks** [comment] 2017-04-20 18:06
No idea, somehow the websocket connection dies shortly after the connection. The issue is not dependent on TLS, subscription or any publishes.

**Comment by prmathur-microsoft** [comment] 2017-04-26 17:40
This issue is blocking us from enabling Websocket over Mqtt. Can someone please take a look at it ?

**Comment by maartenl945** [comment] 2017-05-03 08:31
I get a similar problem here. Initial connect with paho client reports ok, but it is immediately followed by a connection lost callback call. And than a cycle of reconnect attempts repeats every second as we are using the automatic reconnect feature:
```
2017-05-03 08:43:59,356 INFO MQTT Call: 481e630b-e3c5-4962-b691-e9c7663ea948 [com.wps.pms.cloudreportingconnector.mqtt.MqttReportingPublisher] : Connect complete to server ws://host-deleted-on-purpose:8083, reconnect is true, bufferedMessage = 0
 2017-05-03 08:44:00,358 INFO MQTT Rec: 481e630b-e3c5-4962-b691-e9c7663ea948 [com.wps.pms.cloudreportingconnector.mqtt.MqttReportingPublisher] : Connection lost {}
 org.eclipse.paho.client.mqttv3.MqttException: Connection lost
 at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164) [org.eclipse.paho.client.mqttv3-100.1.1.jar:?]
 at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
 Caused by: java.io.EOFException
 at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.7.0_95]
 at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-100.1.1.jar:?]
 at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116) ~[org.eclipse.paho.client.mqttv3-100.1.1.jar:?]
 ... 1 more
```

**Comment by jpwsutton** [comment] 2017-05-03 15:23
Ok, I've been able to recreate this, funny it doesn't show in our unit tests. I'll look into this and see what I can dig out.

**Comment by binarybucks** [comment] 2017-05-03 15:31
It probably wasn't caught because the connection actually works for a short time. 
Before the connection dies, the client even receives messages to retained subscriptions.

**Comment by raipratheek** [comment] 2017-05-05 09:57
I had a similar problem with websocket connection. After connection I was subscribing for a topic and I used to get  this error.
Throwable occurred: Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:128)
	... 3 more

I used a sniffer tool to check the payload and found that the msgID for MQTTSubscribe message is always 0. I changed it to a nonzero number ( like 2) and the problem was solved.

**Comment by raipratheek** [comment] 2017-05-10 18:43
The issue seems to be related to the message ID being 0. The io.netty.handler.codec.mqtt.MqttCodecUtil expects the message ID to be non-zero.

static boolean isValidMessageId(int messageId) {
        return messageId != 0;
    }

**Comment by lelloman** [comment] 2017-05-11 11:22
@raipratheek were you able to fix this within paho client or did you fiddle with the broker?

**Comment by raipratheek** [comment] 2017-05-11 11:34
The changes I made were only within Eclipse Paho. I just made sure none of the requests (PUBLISH, SUBSCRIBE ..etc ) has messageID = 0.

**Comment by lelloman** [comment] 2017-05-11 14:08
@raipratheek just to be clear, you mean that I should force `int msgId` field of `MqttWireMessage` to be not 0?

**Comment by raipratheek** [comment] 2017-05-11 14:15
Yes.. you could do that. Make sure the message ID is the same in all the places it is used. Eg : MqttToken.

**Comment by lelloman** [comment] 2017-05-11 14:22
@raipratheek any chances you could fork with these changes? I'm doing random attempts here but I have no actual understanding of what I'm trying xD

**Comment by raipratheek** [comment] 2017-05-11 14:24
@lelloman I just checked by changing the int msgId in the MqttWireMessage constructor to 2 ( just a number) and it works. No other change required. Could you check with this change ?

public MqttWireMessage(byte type) {
		this.type = type;
		// Use zero as the default message ID.  Can't use -1, as that is serialized
		// as 65535, which would be a valid ID.
		this.msgId = 2;
	}

**Comment by lelloman** [comment] 2017-05-11 14:36
thanks for the input but it doesn't work :( 
the first problem i had with websocket (not with tcp) is that I was getting EOFException in CommsReceiver
```
receiving = in.available() > 0;
MqttWireMessage message = in.readMqttWireMessage();
```
to
```
MqttWireMessage message = null;
try {
	message = in.readMqttWireMessage();
}catch(Exception e){
}
```

and this "solved" the EOFException, now, if i apply only your change i get EOFException again, if i keep the EOFException "solution" and also apply your change it still doesn't receive other messages i'm pushing. my other non-paho-client does receive them though

**Comment by raipratheek** [comment] 2017-05-11 15:10
@lelloman  Could you try the same with the code from the develop branch ? I assume you are using the code from the master.
It works for me here with the code from develop branch after I change the msgId to a non zero number.

**Comment by lelloman** [comment] 2017-05-12 07:40
@raipratheek it did work! do you think this fix will be included in the next release?

**Comment by prmathur-microsoft** [comment] 2017-05-12 17:32
thanks for fixing this. Can you please point me to the branch/commit where this fix is working ? I would like to try it out on my setup as well.

**Comment by raipratheek** [comment] 2017-05-12 19:25
I have made the changes here.
https://github.com/raipratheek/paho.mqtt.java/tree/develop

**Comment by jpwsutton** [comment] 2017-05-15 10:18
Good spot @raipratheek, The 3.1.1 spec shows that we should assign an unused Packet Identifier every time: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349761

The change suggested looks like it would change the behaviour of the code here: https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L482 which relies on a Message ID of 0 before a new Message ID is generated (However, this generation only happens for MqttPublish Messages. I think the real fix should be to add message ID generation for all of the appropriate message types listed in the spec (PUBLISH (where QoS > 0), PUBACK, PUBREC, PUBREL, PUBCOMP, SUBSCRIBE, SUBACK, UNSUBSCRIBE, UNSUBACK)

**Comment by prmathur-microsoft** [comment] 2017-05-16 23:29
Thanks for fixing this. When will these changes be released ? I'm looking for a maven package with these changes.

**Comment by jpwsutton** [comment] 2017-05-17 14:31
@prmathur-microsoft the latest snapshot is available here: https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.1.2-SNAPSHOT/

**Comment by prmathur-microsoft** [comment] 2017-05-17 18:16
@jpwsutton Thanks for the link. Although I can use this for testing and verification purposes, I cannot use a snapshot to be included in my release. Latest I see is v1.1.1. When will there be another release (v1.1.2) containing these changes that I can deploy on my end ?

**Comment by jpwsutton** [comment] 2017-05-22 07:54
The next formal release will be the Paho 1.3 (oxygen) release that will occur this June: https://projects.eclipse.org/projects/iot.paho/releases/1.3.0-oxygen

**Comment by prmathur-microsoft** [comment] 2017-06-29 18:47
I still don't see paho 1.3.0 on maven - http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.paho%22
Has the release been delayed ?

**Comment by prmathur-microsoft** [comment] 2017-07-06 01:13
Can you please let me know when can I see the maven package with this fix ? We are waiting for this fix to enable mqtt with websockets on our side.

**Comment by tameraw** [comment] 2017-07-17 20:23
@jpwsutton @raipratheek - Any update on when we can expect to see the new maven package for this fix?

**Comment by jpwsutton** [comment] 2017-09-08 08:39
@tameraw It's available here: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22org.eclipse.paho.client.mqttv3%22

**Closed as completed by jpwsutton** 2017-09-08 08:39 UTC
Labels: bug, fix submitted
