### ISSUE TITLE
Improper mix of time units in ping subsystem

### ISSUE THREAD

**Issue by geirem** [eclipse-paho/paho.mqtt.java#640] opened 2019-03-21 09:46 UTC
Please fill out the form below before submitting, thank you!

- [] Bug exists Release Version 1.2.0 ( Master Branch)
- [X] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

# Improper mixture of time units in ping schedule

Line [787 of the ClientState class (v1.2.1)](https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L787) uses the equation
`nextPingTime = Math.max(1,  getKeepAlive() - (time - lastOutboundActivity));` to schedule the next ping time.  But `getKeepAlive` is in units of milliseconds, while `lastOutboundActivity` is in units of nanoseconds.  Thus the equation is generally negative, resulting in a value of 1 from the `Math.max` guard.

The end result is that pings are scheduled every millisecond.

## Suggested Solution
Replace the method call `getKeepAlive()` with direct use of the attribute `keepAlive` so that time units are consistent across the equation.

**Comment by marcostorto** [comment] 2020-02-04 17:56
This bug is causing spurious disconnect in our application, as `lastOutboundActivity` can be updated after `checkForActivity` has executed `long time = System.nanoTime();` 
A concurrent call to `notifySentBytes` or `notifySent` will cause `lastOutboundActivity` to be > than `time`  (see attached log snippet https://github.com/eclipse/paho.mqtt.java/files/4155025/log.txt)

In this case `nextPingTime` is set to a very high number, triggering broker timeout

We're working on a fix, we'll submit a PR shortly

**Comment by rdasgupt** [comment] 2020-02-04 19:14
PR for this problem is there:
https://github.com/eclipse/paho.mqtt.java/pull/743

**Comment by rdasgupt** [comment] 2020-04-01 03:46
Duplicate of #738

**Closed as completed by rdasgupt** 2020-04-01 03:46 UTC
Labels: duplicate
